\documentclass[12pt, oldfontcommands]{article}
\usepackage[english]{babel}
%\usepackage[brazilian, brazil]{babel}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{bm}
\usepackage{graphicx}
\usepackage[top = 2cm, left = 2cm, right = 2cm, bottom = 2cm]{geometry}
\usepackage{indentfirst}
\usepackage{float}
\usepackage{multicol}
\usepackage[normalem]{ulem}
\usepackage{breqn}
\usepackage{amsfonts}
\usepackage{amsthm}
\usepackage{enumitem}
\usepackage{booktabs}
\usepackage{threeparttable}
\setlength\parindent{0pt}
\newcommand{\horrule}[1]{\rule{\linewidth}{#1}}

\title{  
 \normalfont \normalsize 
 \textsc{AMCS 210 - Applied Statistics and Data Analysis} \\
 Hernando Catequista Ombao \\
 Applied Mathematics and Computational Sciences Program \\
 Computer, Electrical and Mathematical Sciences \& Engineering (CEMSE) Division \\
 King Abdullah University of Science and Technology (KAUST) \\[25pt]
 \horrule{.5pt} \\ [.4cm]
 \LARGE HOMEWORK \\
  2
 \horrule{2pt} \\[ .5cm]}
 
\author{Henrique Aparecido Laureano}
\date{\normalsize Fall Semester 2017}

\begin{document}

\maketitle

\vspace{\fill}

\tableofcontents

\horrule{1pt} \\

\newpage

<<setup, include=FALSE>>=
# <code r> ===================================================================== #
library(knitr)

tema <- knit_theme$get("acid")

knit_theme$set(tema)

opts_chunk$set(size='small'
               , cache=TRUE
               , cache.path='cache/'
               , comment=NA
               , warning=FALSE
               , message=FALSE
               , fig.align='center'
               , dpi=100
               , fig.path='iBagens/'
               , fig.pos='H'
               , background='#ffffff'
               , results='hold'
               , fig.show='hold')
# </code r> ==================================================================== #
@

\section*{Exercise 1} \addcontentsline{toc}{section}{Exercise 1}

\horrule{1pt} \\

\textbf{A politician running for office is interested in estimating the
        proportion among legal residents of the state of California who support
        the DREAMER’s act (which we denote as \(\pi\)). An organization was
        instructed to conduct a poll with the constraint that the estimator should
        be within a tolerance limit of 0.05.} \\
        
\textbf{Suppose that the true population proportion of supporters is
        \(\pi\) = 0.65. The organization is now at a planning stage to determine
        the desired sample size so that there is only a slim chance of 10\% that
        an estimator (sample proportion) falls outside of the designated tolerance
        limit (i.e., it falls outside of 0.60 and 0.70).}

\subsection*{(a)} \addcontentsline{toc}{subsection}{(a)}

\textbf{Conduct a simulation study to determine if a sample size of n = 200
        respondents will be sufficient to meet the target? As a guide to
        approaching this problem: (i.) simulate at least B = 10.000 samples each
        of size n = 200 from a binomial distribution; (ii.) for each sample record
        the sample proportion; (iii.) determine the proportion (out B = 10.000
        samples) of sample proportion that fall within the designated tolerance
        limit.} \\

\underline{Solution:}

<<>>=
# <code r> ===================================================================== #
## defining some variables
n <- 200 # sample size
B = 1e4 # number of replications
p <- .65 # true proportion
tol <- .05 # tolerance level
in_inter <- numeric(B) # creating empth object of size B

## simulation study code
for (i in 1:B){
  samp <- rbinom(1, n = n, p = p) # simulating samples from a binomal dist.
  prop <- mean(samp) # sample proportion
  abs_samp <- abs(prop - p) # difference to the tolerance level
  in_inter[i] <- ifelse(abs_samp <= tol, "in", "out") # if is in or out
}
# proportion of sample proportion that fall within (or out) the tol. level
prop.table(table(in_inter))
# </code r> ==================================================================== #
@

The proportion is of 14\%, bigger than the desired proportion of 10\%.

\subsection*{(b)} \addcontentsline{toc}{subsection}{(b)}

\textbf{If the sample size of n = 200 does not satisfy the requirement above
        continue with procedure of finding the smallest sample size that would
        satisfy the tolerance limit.} \\

\underline{Solution:}

<<fig.width=10, fig.height=5.25, fig.cap="Sample sizes vs. tolerance limits.">>=
# <code r> ===================================================================== #
final_prop <- prop.table(table(in_inter)) ; prop_out <- final_prop[[2]]
while (final_prop[[2]] > .1){
  for (i in 1:B){
    samp <- rbinom(1, n = n + 1, p = p)
    prop <- mean(samp) ; abs_samp <- abs(prop - p)
    in_inter[i] <- ifelse(abs_samp <= tol, "in", "out")}
  final_prop <- prop.table(table(in_inter))
  prop_out[length(prop_out)+1] <- final_prop[[2]] ; n <- n + 1}
library(latticeExtra)
xyplot(prop_out ~ 200:n, type = c("h", "p"), pch = 16
       , xlab = "Sample size", ylab = "Tolerance limit"
       , main = paste0(
         "Smallest sample size: ", n, " (tolerance limit: ", min(prop_out), ")")
       , scales = list(x = list(at = c(200, n)))
       , panel = function(...){
         panel.abline(h = .1, col = 2, lty = 2)
         panel.xyplot(...)
         panel.segments(n, 0, n, min(prop_out), col = 2, lwd = 2)
         panel.points(n, min(prop_out), col = 2, pch = 16)})
# </code r> ==================================================================== #
@

\section*{Exercise 2} \addcontentsline{toc}{section}{Exercise 2}

\horrule{1pt} \\

\textbf{Exercises on calculating binomial probabilities. Let \(X\) be a binomial
        random variable with n = 5 and probability parameter \(\pi\) = 0.3. Think
        of this as counting the number of heads obtained by tossing n = 5
        identical coins each of which has the probability of \(\pi\) = 0.3 that it
        lands in heads.}

\subsection*{(a)} \addcontentsline{toc}{subsection}{(a)}

\textbf{Enumerate the elements of the sample space of \(X\).} \\

\underline{Solution:}

\[ \Omega = \{0, 1, 2, 3, 4, 5\}. \]

\subsection*{(b)} \addcontentsline{toc}{subsection}{(b)}

\textbf{Obtain the table of probability mass function, i.e., compute the
        probabilities \(\mathbb{P}(X = x)\) for each \(x\) in the sample space.} 
\\

\underline{Solution:}

\begin{minipage}{10cm}
\[ \mathbb{P}(X = x) = \binom{n}{x} \pi^{x} (1 - \pi)^{n-x}
                     = \binom{5}{x} 0.3^{x} (0.7)^{5-x}.
\]
\end{minipage}
\begin{minipage}{6.5cm}
\begin{table}[H]
 \centering
  \begin{tabular}{c|l}
   \toprule
   x & \(\mathbb{P}(X = x)\) \\
   \midrule
   0 & \Sexpr{dbinom(0, 5, .3)} \\
   1 & \Sexpr{dbinom(1, 5, .3)} \\
   2 & \Sexpr{dbinom(2, 5, .3)} \\
   3 & \Sexpr{dbinom(3, 5, .3)} \\
   4 & \Sexpr{dbinom(4, 5, .3)} \\
   5 & \Sexpr{dbinom(5, 5, .3)} \\
   \bottomrule
  \end{tabular}
\end{table}
\end{minipage}

\subsection*{(c)} \addcontentsline{toc}{subsection}{(c)}

\textbf{Compute \(\mathbb{P}(X \geq 4)\).} \\

\underline{Solution:}

\[ \mathbb{P}(X \geq 4) = \mathbb{P}(X = 4) + \mathbb{P}(X = 5)
                        = \Sexpr{dbinom(4, 5, .3)} + \Sexpr{dbinom(5, 5, .3)} \]

\[ \boxed{\mathbb{P}(X \geq 4) = \Sexpr{dbinom(4, 5, .3) + dbinom(5, 5, .3)}.} \]

\subsection*{(d)} \addcontentsline{toc}{subsection}{(d)}

\textbf{Compute \(\mathbb{P}(X < 3)\).} \\

\underline{Solution:}

\[ \mathbb{P}(X < 3) = 1 - \mathbb{P}(X \geq 3)
                     = 1 - [\mathbb{P}(X = 3) + \mathbb{P}(X \geq 4)]
                     = 1 - [\Sexpr{dbinom(3, 5, .3)} +
                            \Sexpr{pbinom(3, 5, .3, lower.tail = FALSE)}
                            ]
                     = 1 -\Sexpr{pbinom(2, 5, .3, lower.tail = FALSE)}
\]
\[ \boxed{\mathbb{P}(X < 3) = \Sexpr{pbinom(2, 5, .3)}.} \]

\section*{Exercise 3} \addcontentsline{toc}{section}{Exercise 3}

\horrule{1pt} \\

\textbf{Exercises on calculating probabilities for the normal distribution. Some
        of these require the use of the standard normal probability table which
        has been uploaded in the subfolder ”Admin” in the class dropbox.}

\subsection*{(a)} \addcontentsline{toc}{subsection}{(a)}

\textbf{Suppose that the systolic blood pressure (SBP) among white teens follows a
        normal distribution with mean \(\mu\) = 120 units (mm Hg) and standard
        deviation \(\sigma\) = 4 units.} \\

\textbf{(i.) What are the first and third quartile SBP values in this population?}
\\

\underline{Solution:} \\

First quartile: \(Q_{1}\), third quartile: \(Q_{3}\)

\[ Z = \frac{Q_{1} - \mu}{\sigma} = \frac{Q_{1} - 120}{4}, \quad
   Z = \frac{Q_{3} - \mu}{\sigma} = \frac{Q_{3} - 120}{4} \]

The \(Z\) value that correspond to 0.25 (first quartile) is -0.67 (using standard
normal probability table), and to 0.75 (third quartile) is 0.67. So,

\begin{minipage}{10cm}
 \[ Q_{1} = Z \cdot \sigma +\mu = -0.67 \cdot 4 + 120, \quad
    Q_{3} = 0.67 \cdot 4 + 120. \]
\end{minipage}
\begin{minipage}{6cm}
 \[ \boxed{Q_{1} = \Sexpr{-.67*4 + 120}, \quad Q_{3} = \Sexpr{.67*4 + 120}.} \]
\end{minipage}

\vspace{.6cm}
\textbf{(ii.) What is the 90-th percentile SBP value?} \\

\underline{Solution:} \\

The \(Z\) value that correspond to 0.9 (90-th percentile, \({\rm perc}_{90}\)) is
1.28 (using standard normal probability table). So, \\

\begin{minipage}{10cm}
 \[ 1.28 = \frac{{\rm perc}_{90} - 120}{4}, \quad
    {\rm perc}_{90} = 1.28 \cdot 4 + 120, \]
\end{minipage}
\begin{minipage}{5cm}
 \[ \boxed{{\rm perc}_{90} = \Sexpr{1.28*4 + 120}.} \]
\end{minipage}

\vspace{.4cm}
\textbf{(iii.) Use the standard normal table to calculate the proportion of teens
               with SBP between 112 and 126 units.} \\

\underline{Solution:} \\

\(X\) = proportion of teens with some quantite of SBP (in units).

\begin{align*}
 \mathbb{P}(112 \leq X \leq 126) & =
 \mathbb{P}\bigg(\frac{112-120}{4} \leq \frac{X-120}{4} \leq \frac{126-120}{4}
           \bigg) = \mathbb{P}\bigg(-2 \leq Z \leq \frac{3}{2}\bigg) \\
  & =  \mathbb{P}(Z \leq 1.5) - \mathbb{P}(Z \leq -2) = 0.9332 - 0.0228
\end{align*}

\[ \boxed{\mathbb{P}(112 \leq X \leq 126) = \Sexpr{.9332 - .0228}.} \]

\vspace{.45cm}
\textbf{(iv.) A teen was randomly selected from the population. What is the
              probability that this teen has SBP that is greater than 130 units?}
\\

\underline{Solution:}

\[ \mathbb{P}(X > 130) = 1 - \mathbb{P}(X \leq 130) = 1 -
   \mathbb{P}\bigg(\frac{X-120}{4} \leq \frac{130-120}{4}\bigg) = 1 -
   \mathbb{P}(Z \leq 2.5) = 1 - 0.9938
\]

\[ \boxed{\mathbb{P}(X > 130) = \Sexpr{1 - .9938}.} \]

\vspace{.45cm}
\textbf{(v.) An investigator randomly selected 5 teens. What is the probability
             that none of them has SBP tha exceeds 130 units?} \\

\underline{Solution:} \\

\(Y\) = number of teens with SBP that exceeds 130 units.

\begin{minipage}{8cm}
 \[ \mathbb{P}(Y = 0) = \binom{5}{0} \Sexpr{1-.9938}^{0} (1-\Sexpr{1-.9938})^{5},
 \]
\end{minipage}
\begin{minipage}{5cm}
 \[ \boxed{\mathbb{P}(Y = 0) = \Sexpr{dbinom(0, 5, 1-.9938)}.} \]
\end{minipage}

\vspace{.45cm}
\textbf{(vi.) Again on the 5 teens: what is the probability that exactly 1 has SBP
              that exceeds 130 units.} \\

\underline{Solution:}

\begin{minipage}{8cm}
 \[ \mathbb{P}(Y = 1) = \binom{5}{1} \Sexpr{1-.9938}^{1} (1-\Sexpr{1-.9938})^{4},
 \]
\end{minipage}
\begin{minipage}{5cm}
 \[ \boxed{\mathbb{P}(Y = 1) = \Sexpr{dbinom(1, 5, 1-.9938)}.} \]
\end{minipage}

\subsection*{(b)} \addcontentsline{toc}{subsection}{(b)}

\textbf{A graduate program will admit only students who score on the top 90-th
        percentile in an international examination. There is some complication in
        the admissions process because the grading scheme for the examination
        changed in 2016. Prior to 2016, the scores ranged from 0 to 800. From 2016
        onwards the scores were recalibrated so that they range from 0 to 150.
        Suppose that the pre-2016 scores followed a normal distribution with mean
        600 and variance of 50. From 2016 onwards the distribution remained normal
        but the mean is 120 and the variance is 15. One applicant who took the
        test in 2015 scored 700 (out of 800) and another who took the test in 2017
        scored 130 (out of 200). Check if either of these applicants should be
        automatically denied admission based on the examination scores.} \\

\underline{Solution:} \\

We have two Normal's, we can call \(X \sim {\rm N}(600, \sqrt{50})\) and
\(Y \sim {\rm N}(120, \sqrt{15})\). In a Standard Normal, \({\rm N}(0, 1)\), the
Z value that correspond to the 90-th percentile, \({\rm perc}_{90}\), is 1.28. \\

For each Normal distributions the 90-th percentiles are:

\[ {\rm perc}_{90} = 1.28 \cdot \sqrt{50} + 600 = \Sexpr{1.28*sqrt(50)+600}, \quad
   {\rm perc}_{90} = 1.28 \cdot \sqrt{15} + 120 = \Sexpr{1.28*sqrt(15)+120}. \]

So, based on the examination scores both applications shouldn't be automatically
denied, because both scores are on the top 90-th percentile in the international
examination.

\section*{Exercise 4} \addcontentsline{toc}{section}{Exercise 4}

\horrule{1pt} \\

\textbf{Download the “wdbc” data set. Provide a bar graph for the discrete
        variable, and scatter plots for each pair of continuous variables. Provide
        the box plots of continuous variables for each level of “Diagnosis”. In
        one paragraph, discuss your findings based on these graphs.} \\

\underline{Solution:}

<<fig.width=10, fig.height=4.25, fig.cap='Frequency and percentage for each level of "Diagnosis".'>>=
# <code r> ===================================================================== #
library("kdevine") ; data(wdbc)

barchart(wdbc$diagnosis, col = "#0080ff", xlab = "Frequency", xlim = c(0, 410)
         , scales = list(x = list(draw = FALSE)
                         , y = list(labels = c("Benign", "Malignant")))
         , border = "transparent", main = "Diagnosis"
         , panel = function(...){
           args <- list(...)
           panel.text(args$x, args$y, pos = 4
                      , paste0(args$x," (", round(prop.table(args$x),3)*100,"%)"))
           panel.barchart(...)})
# </code r> ==================================================================== #
@

This dataset contain measurements on cells in suspicious lumps in a women's
breast. Variables are computed from a digitized image of a fine needle aspirate
(FNA) of a breast mass. They describe characteristics of the cell nuclei present
in the image. All samples are classsified as either \textit{benign} or
\textit{malignant}. \\

Ten real-valued variables are computed for each cell nucleus. \\

The mean, standard error, and "worst" or largest (mean of the three largest
values) of these variables were computed for each image, resulting in 30
variables. \\

This breast cancer database was obtained from the University of Wisconsin
Hospitals, Madison from Dr. William H. Wolberg. \\

Thus, we provide the scatter plots for each pair of variables divided by the
mean, standard error and "worst" values, resulting in this way in three scatter
plot matrices.

\vspace{1.75cm}

<<fig.width=10, fig.height=10, fig.cap="Scatter plots for each pair of mean variables in the lower triangular part of the matrix, in the upper triangular part we have the respectives correlations between the variables. In blue we have the corresponding observations to the benign diagnosis and in gray the corresponding observations to the malignant diagnosis.">>=
# <code r> ===================================================================== #
panel.cor <- function(x, y, ...){
  usr <- par("usr")
  on.exit(par(usr))
  par(usr = c(0, 1, 0, 1))
  r <- abs(cor(x, y))
  txt <- format(c(r, 0.123456789), digits = 2)[1]
  text(0.5, 0.5, txt, cex = .8/strwidth(txt))
}
rotulos <- tm::removeWords(names(wdbc[2:11]), "mean ")
rotulos[c(5:6, 8, 10)] <- c("smooth", "compact", "concave", "fractal d.")

pairs(wdbc[2:11]
      , pch = 16
      , gap = .25
      , las = 1
      , upper.panel = panel.cor
      , col = c("#0080ff", "gray30")[unclass(wdbc$diagnosis)]
      , labels = rotulos
      , font.labels = 2
      , main = "Mean")
# </code r> ==================================================================== #
@

\vspace{-.5cm}
<<fig.width=10, fig.height=10, fig.cap='Scatter plots for each pair of "worst" variables in the lower triangular part of the matrix, in the upper triangular part we have the respectives correlations between the variables. In blue we have the corresponding observations of the benign diagnosis and in gray the corresponding observations of the malignant diagnosis.'>>=
# <code r> ===================================================================== #
rotulos <- tm::removeWords(names(wdbc[12:21]), "worst ")
rotulos[c(5:6, 8, 10)] <- c("smooth", "compact", "concave", "fractal d.")

pairs(wdbc[12:21], pch = 16, gap = .25, las = 1, upper.panel = panel.cor
      , col = c("#0080ff", "gray30")[unclass(wdbc$diagnosis)]
      , labels = rotulos, font.labels = 2, main = '"Worst"')
# </code r> ==================================================================== #
@

<<fig.width=10, fig.height=10, fig.cap="Scatter plots for each pair of standard error variables in the lower triangular part of the matrix, in the upper triangular part we have the respectives correlations between the variables. In blue we have the corresponding observations to the benign diagnosis and in gray the corresponding observations to the malignant diagnosis.">>=
# <code r> ===================================================================== #
rotulos <- tm::removeWords(names(wdbc[22:31]), "sd ")
rotulos[c(5:6, 8, 10)] <- c("smooth", "compact", "concave", "fractal d.")
pairs(wdbc[22:31], pch = 16, gap = .25, las = 1, upper.panel = panel.cor
      , col = c("#0080ff", "gray30")[unclass(wdbc$diagnosis)]
      , labels = rotulos, font.labels = 2, main = "Standard error")
# </code r> ==================================================================== #
@

\newpage
Box plots:

<<fig.width=10, fig.cap='Box plots for each mean variable divided by "Diagnosis".'>>=
# <code r> ===================================================================== #
wdbc_mean <- reshape2::melt(wdbc[1:11], id.vars = "diagnosis")
levels(wdbc_mean$diagnosis) <- c("Benign", "Malignant")
levels(wdbc_mean$variable) <- tm::removeWords(levels(wdbc_mean$variable), "mean ")

bwplot(value ~ diagnosis | variable, wdbc_mean
       , layout = c(4, 3), scales = list(y = list(relation = "free", rot = 0))
       , ylab = NULL, strip = strip.custom(bg = "white"), pch = "|"
       , main = "Mean"
       , par.settings = list(
         box.rectangle = list(
           col = c("#0080ff", "gray60"), fill = c("#0080ff", "gray60")
           , alpha = .6, border = "transparent")
         , box.umbrella = list(col = c("#0080ff", "gray60"))
         , plot.symbol = list(col = "red", pch = 16, alpha = .6)))
# </code r> ==================================================================== #
@

<<fig.width=10, fig.cap='Box plots for each "worst" variable divided by "Diagnosis".'>>=
# <code r> ===================================================================== #
wdbc_worst <- reshape2::melt(wdbc[c(1, 12:21)], id.vars = "diagnosis")
levels(wdbc_worst$diagnosis) <- c("Benign", "Malignant")
levels(wdbc_worst$variable) <-
  tm::removeWords(levels(wdbc_worst$variable), "worst ")

bwplot(value ~ diagnosis | variable, wdbc_worst
       , layout = c(4, 3), scales = list(y = list(relation = "free", rot = 0))
       , ylab = NULL, strip = strip.custom(bg = "white"), pch = "|"
       , main = '"Worst"'
       , par.settings = list(
         box.rectangle = list(
           col = c("#0080ff", "gray60"), fill = c("#0080ff", "gray60")
           , alpha = .6, border = "transparent")
         , box.umbrella = list(col = c("#0080ff", "gray60"))
         , plot.symbol = list(col = "red", pch = 16, alpha = .6)))
# </code r> ==================================================================== #
@

<<fig.width=10, fig.cap='Box plots for each standard error variable divided by "Diagnosis".'>>=
# <code r> ===================================================================== #
wdbc_sd <- reshape2::melt(wdbc[c(1, 22:31)], id.vars = "diagnosis")
levels(wdbc_sd$diagnosis) <- c("Benign", "Malignant")
levels(wdbc_sd$variable) <- tm::removeWords(levels(wdbc_sd$variable), "sd ")

bwplot(value ~ diagnosis | variable, wdbc_sd
       , layout = c(4, 3), scales = list(y = list(relation = "free", rot = 0))
       , ylab = NULL, strip = strip.custom(bg = "white"), pch = "|"
       , main = "Standard error"
       , par.settings = list(
         box.rectangle = list(
           col = c("#0080ff", "gray60"), fill = c("#0080ff", "gray60")
           , alpha = .6, border = "transparent")
         , box.umbrella = list(col = c("#0080ff", "gray60"))
         , plot.symbol = list(col = "red", pch = 16, alpha = .6)))
# </code r> ==================================================================== #
@

Approximatelly 2/3 of the patients were with the exam classified as benign. When
we look to the mean variables, three pairs present a correlation (linear
correspondence) extremaly close to 1. Between this ten variables we see every
behavior types. Relations with a very high correlation, with a medium correlation
and with a very small correlation. In general, the same behavior is seen with the
same variables when we looked to the "worst" and standard error variables. We can
highlight as very high correlations the relations between the variables area and
perimeter, radius and perimeter, and radius and area. As a very small correlation
we can highlight the relations between the variables texture and symmetry, texture
and fractal dimension, area and symmetry, and area and fractal dimension. When we
looked to the box plots, in general, for all the ten variables in the three
different measure types, the biggest values are present in the patients
classified as malignant.

\section*{Exercise 5} \addcontentsline{toc}{section}{Exercise 5}

\horrule{1pt} \\

\textbf{Consider this dataset derived from the Framingham Heart Study where one of
        the goals was to study possible links between high systolic blood pressure
        (SBP) and coronary heart disease (CHD). Participants with SBP \(\geq\) 165
        mm Hg were put in the ”high” SBP category.}

\begin{center}
 \begin{tabular}{|c|c|c|}
  \hline
  & CHD & No CHD \\ \hline
  High SBP & 144 & 62 \\ \hline
  Normal SBP & 120 & 419 \\
  \hline
 \end{tabular}
\end{center}

\subsection*{(a)} \addcontentsline{toc}{subsection}{(a)}

\textbf{\textit{Marginal proportions}. From the table, what is the proportion of
        participants who had CHD? What is the proportion of participants who had
        high SBP?} \\

\underline{Solution:} \\

CHD = 144 + 120 = 264, \quad NoCHD = 62 + 419 = 481, \quad n = CHD + NoCHD = 745
\\

\boxed{\text{Proportion of participants who had CHD: CHD/n = 264/745 = 0.3543624
             (35\%).}} \\

HiSBP = 144 + 62 = 206, \quad NorSBP = 120 + 419 = 539, \\
n = CHD + NoCHD = HiSBP + NorSBP = 745 \\

\boxed{\text{Proportion of participants who had high SBP:
             HiSBP/n = 206/745 = 0.2765101 (28\%).}}
   
\subsection*{(b)} \addcontentsline{toc}{subsection}{(b)}

\textbf{\textit{Conditional proportions}. Among the participants with high SBP,
        what is the proportion of those who also have CHD? Among the participants
        with normal SBP, what is the proportion of those who also have CHD? Does
        this provide some evidence of a link between elevated systolic blood
        pressure and coronary heart disease? Can one now claim that elevated
        systolic blood pressure \underline{causes} coronary heart disease?} \\
        
\underline{Solution:} \\

\fbox{\begin{minipage}{15cm}
       Among the participants with high SBP, the proportion of those who also have
       CHD: \\
       CHD/HiSBP = 144/206 = 0.6990291 (70\%). 
      \end{minipage}} \\

\fbox{\begin{minipage}{15.5cm}
       Among the participants with normal SBP, the proportion of those who also
       have CHD: \\
       CHD/NorSBP = 120/539 = 0.2226345 (22\%). 
      \end{minipage}} \\

Does this provide some evidence of a link between elevated systolic blood pressure
and coronary heart disease? Yes. Because in the patients with normal SBP the
proportion with CHD is 22 percent, almost 1/5, while in the patients with high SBP
the proportion with CHD is 70 percent, much higher. \\

Can one now claim that elevated systolic blood pressure causes coronary heart
disease? No. With this descriptive analysis we can see a possible correlation 
between high SBP and CHD, but this not implies in causality. we don't have enough
information to claim this type of result. Correlation is different form causality.

\subsection*{(c)} \addcontentsline{toc}{subsection}{(c)}

\textbf{\textit{Odds and odds ratios}. Compute the odds of having CHD among the
        high SBP group. Compute the odds of having CHD among the normal SBP group.
        Compute the odds ratio of having CHD for the high SBP vs normal SBP
        groups.} \\
        
\underline{Solution:} \\

\fbox{\begin{minipage}{8.25cm}
       Odds of having CHD among the high SBP group:
       \[ \frac{144/206}{1 - 144/206} = 2.322581. \]
      \end{minipage}} \hfill
\fbox{\begin{minipage}{8.25cm}
       Odds of having CHD among the normal SBP group:
       \[ \frac{120/539}{1 - 120/539} = 0.2863962. \]
      \end{minipage}} \\

\begin{center}
 \fbox{\begin{minipage}{12.25cm}
        Odds ratio of having CHD for the high SBP vs normal SBP groups:
        \[ \frac{2.322581}{0.286396} = 8.109678. \]
       \end{minipage}}
\end{center}

The odds of having CHD for the high SBP groups is 8.11 times of the odds of CHD
for the normal SBP group.

\section*{Exercise 6} \addcontentsline{toc}{section}{Exercise 6}

\horrule{1pt} \\

\textbf{The beetle mortality data. Groups of beetles were exposed to varying doses
        of toxins and the number of deaths (\texttt{ytotal}) out of the total
        exposure (\texttt{ntotal}) were recorded. Enter the variables in R:}

\begin{align*}
 \texttt{dose} & = {\rm c}(1.69, 1.72, 1.75, 1.78, 1.81, 1.84, 1.86, 1.88) \\
 \texttt{ntotal} & = {\rm c}(59, 60, 62, 56, 63, 59, 62, 60) \\
 \texttt{ytotal} & = {\rm c}(6, 13, 18, 28, 52, 53, 61, 60)
\end{align*}

<<>>=
# <code r> ===================================================================== #
dose <- c(1.69, 1.72, 1.75, 1.78, 1.81, 1.84, 1.86, 1.88)
ntotal <- c(59, 60, 62, 56, 63, 59, 62, 60)
ytotal <- c(6, 13, 18, 28, 52, 53, 61, 60)
# </code r> ==================================================================== #
@

\subsection*{(a)} \addcontentsline{toc}{subsection}{(a)}

\textbf{Calculate the proportion of deaths for each dose-group.} \\

\underline{Solution:}

<<>>=
# <code r> ===================================================================== #
rbind(dose, "death proportion" = round(ytotal/ntotal, 2))
# </code r> ==================================================================== #
@

\subsection*{(b)} \addcontentsline{toc}{subsection}{(b)}

\textbf{Plot the proportion of deaths against dose. Describe the trend: is it
        increasing/ decreasing, is there an asymptote feature?} \\

\underline{Solution:}

<<fig.width=10, fig.height=5, fig.cap="Proportion of deaths against dose.">>=
# <code r> ===================================================================== #
xyplot(ytotal/ntotal ~ dose, type = c("p", "l")
       , pch = 19, lwd = 1.5, xlab = "Dose", ylab = "Proportion of deaths"
       , scales = list(x = list(at = dose))
       , panel = function(...){
         panel.abline(v = dose, h = seq(.2, 1, .2), col = "gray70")
         panel.xyplot(...)})
# </code r> ==================================================================== #
@

The trend is increasing. For small doses the proportions are very close to zero,
with the biggest doses the proportions are very close to one. With the last dose 
we have a proportion equal to one, the maximum possible. Whats means that with the
biggest dose all the beetles are dead.

\hfill \(\blacksquare\)

\horrule{.5pt}

\vspace{\fill}

\horrule{1pt} \\

\end{document}